######### 锚点 start #######
# 策略组相关
default-proxies: &default-proxies {type: select, proxies: [默认选择, 原生加速, 倍率专线, 亚太快速, 欧美优选, AI专线, 其它地区, 自动选择, 故障转移, 负载均衡, 手动选择, 直接连接]}
priority-direct: &priority-direct {type: select, proxies: [直接连接, 默认选择, 原生加速, 倍率专线, 亚太快速, 欧美优选, AI专线, 其它地区, 自动选择, 故障转移, 负载均衡, 手动选择]}
unlock-ai: &unlock-ai {type: select, proxies: [AI专线, 默认选择, 原生加速, 倍率专线, 亚太快速, 欧美优选, 其它地区, 自动选择, 故障转移, 负载均衡, 手动选择, 直接连接]}
# unlock-streaming: &unlock-streaming {type: select, proxies: [默认选择, 原生加速, 倍率专线, 亚太快速, 欧美优选, AI专线, 其它地区, 自动选择, 故障转移, 负载均衡, 手动选择, 直接连接]}
consistent-hashing: &consistent-hashing {type: select, proxies: [负载均衡, 默认选择, 原生加速, 倍率专线, 亚太快速, 欧美优选, AI专线, 其它地区, 自动选择, 故障转移, 手动选择, 直接连接]}
priority-reject: &priority-reject {type: select, proxies: [REJECT, 直接连接, 默认选择, 原生加速, 倍率专线, 亚太快速, 欧美优选, AI专线, 其它地区, 自动选择, 故障转移, 负载均衡, 手动选择]}
#这里是订阅更新和延迟测试相关的
health-check-gstatic: &health-check-gstatic {type: http, interval: 3600, health-check: {enable: true, url: "https://www.gstatic.com/generate_204", interval: 300}}
######### 锚点 end #######

# url 里填写自己的订阅,名称不能重复
proxy-providers:
  provider1:
    <<: *health-check-gstatic
    url: ""
  provider2:
    <<: *health-check-gstatic
    url: ""
ipv6: true
allow-lan: true
mixed-port: 7890
external-ui: ./dashboard
external-controller: 0.0.0.0:9090
profile:
  store-selected: true
  store-fake-ip: true

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    # 以下域名列表参考自 vernesong/OpenClash 项目，并由 Hackl0us 整理补充
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - 'msftconnecttest.com'
    - 'msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - '*.*.xboxlive.com'
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    - '+.nflxvideo.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.mcdn.bilivideo.cn'
    - 'public.easytier.cn'
    - WORKGROUP
  # dns 服务监听
  listen: 0.0.0.0:1053
  use-hosts: true
  default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1
    - system 
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

  # 当 fallback 参数被配置时, DNS 请求将同时发送至上方 nameserver 列表和下方 fallback 列表中配置的所有 DNS 服务器.
  # 当解析得到的 IP 地址的地理位置不是 CN 时，clash 将会选用 fallback 中 DNS 服务器的解析结果。
  # fallback:
  #   - https://dns.google/dns-query

  # 如果使用 nameserver 列表中的服务器解析的 IP 地址在下方列表中的子网中，则它们被认为是无效的，
  # Clash 会选用 fallback 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 true 且 IP 地址的地理位置为 CN 时，
  # Clash 会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 false, 如果解析结果不在 fallback-filter.ipcidr 范围内，
  # Clash 总会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 采取以上逻辑进行域名解析是为了对抗 DNS 投毒攻击。
  fallback-filter:
    geoip: false
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.githubusercontent.com'
      - '+.googlevideo.com'

proxies:
- name: "直接连接"
  type: direct
  udp: true
proxy-groups:
- {name: 默认选择, type: select, proxies: [自动选择, 原生加速, 倍率专线, 亚太快速, 欧美优选, AI专线, 其它地区, 故障转移, 负载均衡, 手动选择, 直接连接],
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Proxy.png"}
- {name: 学术开发, <<: *default-proxies,
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Lab.png"}
# - {name: 网上服务, <<: *default-proxies,
#  icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/PayPal.png"}
- {name: 人工智能, <<: *unlock-ai,
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Bot.png"}
- {name: 社交媒体, <<: *default-proxies,
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Twitter.png"}
- {name: 游戏加速, <<: *default-proxies,
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Game.png"}
- {name: 网络存储, <<: *default-proxies,
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/iCloud.png"}
- {name: 影音娱乐, <<: *default-proxies,
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/YouTube.png"}
- {name: NSFW, <<: *consistent-hashing,
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Pornhub.png"}
- {name: 国内流量, <<: *priority-direct,
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/China_Map.png"}
- {name: 广告阻断, <<: *priority-reject,
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/AdBlack.png"}
- {name: 其他流量, <<: *default-proxies,
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Final.png"}
  # 地区分组：原生加速, 倍率专线, 亚太快速, 欧美优选, AI专线, 其它地区, 自动选择, 故障转移, 负载均衡, 手动选择
- {name: 订阅信息, type: select, include-all: true, filter: "(?i)剩余|套餐|通知|官网|客服|发布|网址",  
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Server.png"}
- {name: 原生加速, type: select, include-all: true, filter: "(?i)(原生|混合负载|全球加速|动态加速|智能路由)",
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Airport.png"}
- {name: 倍率专线, type: select, include-all: true, filter: "(?i)(专|專|[xX]\\d+)",
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/VIP.png"}
- {name: 亚太快速, type: url-test, include-all: true, tolerance: 100, lazy: true, filter: "(?i)(港|hk|hongkong|hong kong|台|tw|taiwan|日|jp|japan|韩|kr|新加坡|sg|singapore|越南|vn|vietnam)",
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Speedtest.png"}
- {name: 欧美优选, type: fallback, include-all: true, interval: 300, filter: "(?i)(英|uk|美|us|unitedstates|united states)",
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/United_Kingdom.png"}
- {name: AI专线, type: select, include-all: true, interval: 300, filter: "(?i)(ChatGPT|Sora)",
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Unlock.png"}
- {name: 其它地区, type: select, include-all: true, filter: "(?i)^(?!.*(?:直接连接|剩余|套餐|通知|官网|客服|发布|网址|原生|混合负载|全球加速|动态加速|智能路由|专|專||[xX]\\d+|🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|韩|kr|新加坡|sg|singapore|美|us|unitedstates|英|uk|越南|vn|vietnam|ChatGPT|Sora)).*",
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Available.png"}
- {name: 自动选择, type: url-test, include-all: true, tolerance: 100, lazy: true, filter: "(?i)^(?!.*(?:直接连接)).*",
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Auto.png"}
- {name: 故障转移, type: fallback, include-all: true, interval: 300, filter: "(?i)^(?!.*(?:直接连接)).*",
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Loop.png"}
- {name: 负载均衡, type: load-balance, include-all: true, strategy: consistent-hashing, filter: "(?i)^(?!.*(?:直接连接)).*",
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Static.png"}
- {name: 手动选择, type: select, include-all: true, filter: "(?i)^(?!.*(?:直接连接)).*",
 icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Global.png"}

rules:
# 1. 直接连接 (Bypass LAN and Private)
  - GEOSITE,category-public-tracker,直接连接,no-resolve
  - GEOSITE,category-pt,直接连接,no-resolve
  - GEOSITE,private,直接连接,no-resolve
  - GEOIP,private,直接连接,no-resolve
  - GEOIP,lan,直接连接,no-resolve
  - DOMAIN-SUFFIX,live.cn,直接连接
  - DOMAIN-KEYWORD,aria2,直接连接
  - DOMAIN-SUFFIX,smtp,直接连接
# 2. 广告与跟踪器阻断 (Block)
  - GEOSITE,category-ads-all,广告阻断
  - GEOSITE,win-spy,广告阻断
  - GEOSITE,adobe,广告阻断
  - RULE-SET,reject,广告阻断
# 3. 代理分流 (Proxy Groups)
# - 提前分配：
# - 国内流量 (Domestic)
  # geosite
  - GEOSITE,cloudflare@cn,国内流量
  - GEOSITE,microsoft@cn,国内流量
  - GEOSITE,apple@cn,国内流量
  - GEOSITE,bing@cn,国内流量
  - GEOSITE,CN,国内流量
  # category
  - GEOSITE,category-game-platforms-download,国内流量
  - GEOSITE,category-game-accelerator-cn,国内流量
  - GEOSITE,category-collaborate-cn,国内流量
  - GEOSITE,category-companies@cn,国内流量
  - GEOSITE,category-ecommerce@cn,国内流量
  - GEOSITE,category-documents-cn,国内流量
  - GEOSITE,category-scholar-cn,国内流量
  - GEOSITE,category-media-cn,国内流量
  - GEOSITE,category-games@cn,国内流量
  - GEOSITE,category-games-cn,国内流量
  - GEOSITE,category-bank-cn,国内流量
  - GEOSITE,category-cdn-cn,国内流量
  - GEOSITE,category-dev-cn,国内流量
  - GEOSITE,category-dev@cn,国内流量
  - GEOIP,CN,国内流量
# - 人工智能 (AI)
  - GEOSITE,category-ai-!cn,人工智能
  - GEOSITE,microsoft,人工智能
  - GEOSITE,google,人工智能
  - GEOIP,google,人工智能
# - 学术开发 (Academic)
  - GEOSITE,category-android-app-download,学术开发
  - GEOSITE,category-password-management,学术开发
  - GEOSITE,category-scholar-!cn,学术开发
  - GEOSITE,category-cryptocurrency,学术开发
  - GEOSITE,category-anticensorship,学术开发
  - GEOSITE,category-tech-media,学术开发
  - GEOSITE,category-dev,学术开发
  - GEOSITE,github,学术开发
# - 网络存储 (Cloud Storage)
  - GEOSITE,category-emby,网络存储
  - GEOSITE,onedrive,网络存储
  - GEOSITE,dropbox,网络存储
  - GEOSITE,pikpak,网络存储
  - GEOSITE,mega,网络存储
# - 社交媒体 (Social Media)
  - GEOSITE,category-social-media-!cn,社交媒体
  - GEOSITE,telegram,社交媒体
  - GEOSITE,discord,社交媒体
  - GEOSITE,reddit,社交媒体
  - GEOIP,facebook,社交媒体
  - GEOIP,telegram,社交媒体
  - GEOIP,twitter,社交媒体
# - 游戏加速 (Game Acceleration)
  - GEOSITE,category-games-!cn,游戏加速
# - 影音娱乐 (Entertainment)
  - GEOSITE,category-entertainment@!cn,影音娱乐
  - GEOSITE,category-acg,影音娱乐
  - GEOSITE,biliintl,影音娱乐
  - GEOIP,netflix,影音娱乐
# - NSFW (Adult Content)
  - GEOSITE,category-porn,NSFW
  - GEOSITE,ehentai,NSFW
  - GEOSITE,pixiv,NSFW
# - 其他流量 (Other)
  - GEOSITE,geolocation-!cn,其他流量
  - GEOIP,!cn,其他流量,no-resolve
  - MATCH,其他流量

geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: text}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: text}
rule-providers:
  reject:
    <<: *domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
  direct:
    <<: *domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
